apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.config.PORT }}
      targetPort: {{ .Values.config.PORT }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
